// ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/generateRegistry.ts
// Regenerate by running: pnpm run generate:registry

import type { BlockchainAdapter } from '../core/adapter';
import { getAssetConfig } from '@fireblocks-recovery/assets-evm-btc';

import { BitcoinAdapter } from '../chains/bitcoin';


/**
 * Registry for non-EVM blockchain adapters
 * EVM chains are auto-registered from the assets package in blockchainRegistry.ts
 */
export const NON_EVM_ADAPTERS: Record<string, BlockchainAdapter> = {};

  const btcAsset = getAssetConfig('BTC');
  if (btcAsset && btcAsset.type === 'native') {
    NON_EVM_ADAPTERS['BTC'] = new BitcoinAdapter(btcAsset);
  }



export function registerNonEVMAdapters(registry: Record<string, BlockchainAdapter>): void {
  Object.assign(registry, NON_EVM_ADAPTERS);
}
