// ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/generateRegistry.ts
// Regenerate by running: pnpm run generate:registry

import type { TokenStandard } from '../core/tokenStandard';
import { getAssetConfig } from '@fireblocks-recovery/assets-evm-btc';
import { ERC20Standard } from '../chains/ethereum/tokenStandards/erc20';

/**
 * Base registry with all discovered token standards
 */
const BASE_TOKEN_STANDARDS: Record<string, TokenStandard> = {};

/**
 * Auto-discovered token standards - instantiate and register
 */
const erc20Standard = new ERC20Standard();

BASE_TOKEN_STANDARDS['ETH:ERC20'] = erc20Standard;
BASE_TOKEN_STANDARDS['SGB:ERC20'] = erc20Standard;


/**
 * Check if a blockchain is EVM-compatible
 */
function isEVMCompatible(blockchainId: string): boolean {
  const config = getAssetConfig(blockchainId);
  if (!config || config.type !== 'native') return false;
  // EVM chains use ECDSA with coinType 60 (mainnet) or 1 (testnet)
  return config.algorithm === 'ECDSA' && (config.coinType === 60 || config.coinType === 1);
}

/**
 * Get token standard by key (e.g., "ALGO:ASA" or "ETH:ERC20")
 */
export function getTokenStandard(key: string): TokenStandard {
  // Check if explicitly registered
  if (key in BASE_TOKEN_STANDARDS) {
    return BASE_TOKEN_STANDARDS[key];
  }

  // Parse the key to get blockchain and standard
  const [blockchainId, standardId] = key.split(':');

  // Auto-detect ERC20 for any EVM-compatible chain (mainnet or testnet)
  if (standardId === 'ERC20' && isEVMCompatible(blockchainId)) {
    return BASE_TOKEN_STANDARDS['ETH:ERC20'] || BASE_TOKEN_STANDARDS['SGB:ERC20'];
  }

  // Fallback: token-standard address logic is network-agnostic, so a testnet
  // variant (e.g. TRX_TEST:TRC20, SOL_TEST:SPL, ALGO_TEST:ASA) reuses the same
  // canonical standard already registered for the mainnet chain.
  const canonical = Object.entries(BASE_TOKEN_STANDARDS).find(
    ([k]) => k.split(':')[1] === standardId
  );
  if (canonical) return canonical[1];

  throw new Error(`Unsupported token standard: ${key}`);
}

export function getTokenStandardByBlockchain(
  blockchainId: string,
  standardId: string
): TokenStandard {
  const key = `${blockchainId}:${standardId}`;
  return getTokenStandard(key);
}

export function getAllTokenStandards(): TokenStandard[] {
  return Object.values(BASE_TOKEN_STANDARDS);
}

export function getTokenStandardsForBlockchain(blockchainId: string): TokenStandard[] {
  return getAllTokenStandards().filter(
    (standard) => standard.blockchainId === blockchainId
  );
}

export function isTokenStandardSupported(key: string): boolean {
  return key in BASE_TOKEN_STANDARDS;
}

export const TOKEN_STANDARD_REGISTRY = BASE_TOKEN_STANDARDS;
